# Generated by Django 4.2.4 on 2023-09-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30, verbose_name='Nombre del Tipo de Artículo')),
            ],
            options={
                'verbose_name': 'Tipo de Artículo',
                'verbose_name_plural': 'Tipos de Artículos',
                'db_table': 'article_type',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='destiny',
            name='articulo_entregado',
        ),
        migrations.RemoveField(
            model_name='detailevent',
            name='cantidad_comida',
        ),
        migrations.RemoveField(
            model_name='detailevent',
            name='cantidad_ropa',
        ),
        migrations.RemoveField(
            model_name='detailevent',
            name='comida_evento',
        ),
        migrations.RemoveField(
            model_name='detailevent',
            name='ropa_evento',
        ),
        migrations.RemoveField(
            model_name='detailevent',
            name='tipo_comida',
        ),
        migrations.AddField(
            model_name='destiny',
            name='id_articulo_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.article', verbose_name='Artículo'),
        ),
        migrations.RemoveField(
            model_name='detaildelivery',
            name='id_articulofk',
        ),
        migrations.RemoveField(
            model_name='detailevent',
            name='idarticulo_fk',
        ),
        migrations.AlterField(
            model_name='article',
            name='tipo_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articletype', verbose_name='Tipo de Artículo'),
        ),
        migrations.AddField(
            model_name='detaildelivery',
            name='id_articulofk',
            field=models.ManyToManyField(to='core.article', verbose_name='Artículos'),
        ),
        migrations.AddField(
            model_name='detailevent',
            name='idarticulo_fk',
            field=models.ManyToManyField(to='core.article', verbose_name='Artículos'),
        ),
    ]
