# Generated by Django 4.2.4 on 2023-09-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articletype_remove_destiny_articulo_entregado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='estado_actividad',
        ),
        migrations.AddField(
            model_name='article',
            name='descripcion',
            field=models.TextField(default='', max_length=100, verbose_name='Descripción'),
        ),
    ]
